# Generated by Django 4.0.6 on 2022-07-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfnSpecification',
            fields=[
                ('region_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='RegionName')),
            ],
        ),
        migrations.CreateModel(
            name='CfnResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.TextField(verbose_name='ResourceType')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cfnspecification')),
            ],
        ),
        migrations.CreateModel(
            name='CfnResourceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.TextField(verbose_name='AttributeType')),
                ('attribute_name', models.TextField(verbose_name='AttributeName')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cfnresourcetype')),
            ],
        ),
    ]
