# Generated by Django 4.0.6 on 2022-07-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_cfnresourcetype_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfnresourceattribute',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_attributes', to='backend.cfnresourcetype'),
        ),
    ]
