# Generated by Django 4.1 on 2022-08-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cfnresourceattribute_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='backend.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='cfnresourcetype',
            name='spec',
        ),
        migrations.DeleteModel(
            name='CfnResourceAttribute',
        ),
        migrations.DeleteModel(
            name='CfnResourceType',
        ),
        migrations.DeleteModel(
            name='CfnSpecification',
        ),
    ]
