# Generated by Django 4.1 on 2022-08-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_project_template_remove_cfnresourcetype_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='File'),
        ),
    ]
