# Generated by Django 4.1 on 2022-08-27 03:24

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, upload_to=backend.models.Template.upload_location, verbose_name='File'),
        ),
    ]
